### ISSUE TITLE
Crash when viewing a chat thread

### ISSUE THREAD

**Issue by gnawh** [iandwelker/smserver#28]
Clicking on any chat thread crashes the app on iphone, causing an error on the server as well:
`The server restarted, you need to reload and re-authenticate. (fetch_texts func)`

iPhone 11 Pro Max, 13.5

No settings change this fact. Latest version of both SMServer and dependencies.

**Comment by iandwelker** [comment]
Is the server running in the background when you try this or is it in the foreground?

**Comment by gnawh** [comment]
Same thing happens when in background or foreground, different combination of settings used.
I'm on Odyssey 1.0.1.

**Comment by iandwelker** [comment]
Hmmm well I haven't tested with Odyssey at all yet, so it may just be the way Odyssey works. If you can get me a log of what shows during when you try to select a conversation, that would be great; it would help me to determine the root cause.

**Comment by justin0386** [comment]
I am having this problem now as well but it does it when I try to send messages and crashes the app

**Comment by iandwelker** [comment]
@justin0386 as I mentioned to gnawh, I would much appreciate it if you could get me a log to look at. That'll help me quite a bit in finding the cause.

**Comment by justin0386** [comment]
@iandwelker [https://imgur.com/a/b2G6LYh](url)

**Comment by iandwelker** [comment]
Sorry, maybe I wasn't clear enough; on the readme of this repo, underneath the `To file an issue` section, there are instructions about the kind of log I'm looking for and how to get it. Could you follow those instructions to get a log?

**Comment by justin0386** [comment]
I can do that. then send it to you on reddit?

**Comment by iandwelker** [comment]
yes, you could do that (for privacy), or search through the text file and filter out any potentially sensitive information. It's up to you.

**Comment by justin0386** [comment]
Ok ill will just send on reddit. A few other quick questions. for running the command as root I just log into terminal with my password right then run the command with sudo at the beginning? also I do oslog --debug first then the other command 2nd after I run that one or is it all just one command?

**Comment by iandwelker** [comment]
Well, after you've logged in to your terminal, you can determine who you are by running the command `whoami`. If it prints out `root`, you're good and you don't need to run it with sudo. If it prints out something else, such as `mobile`, you'll need to run it with sudo. And that is all one command, you can just copy and paste `oslog --debug | grep -i -e "SMServer_app" -e "mryipc"` directly into your terminal and hit enter (once you've done the previous step, of course).

**Comment by justin0386** [comment]
![IMG_3416](https://user-images.githubusercontent.com/29316353/91912602-900e1600-ec81-11ea-989b-77f73b9778e6.PNG) Ok I ran the command but it didn't do anything.

**Comment by justin0386** [comment]
Sep  1 20:15:18 Justins-iPhone SMServer(com.ianwelker.smserver.debugging)[32742] <Debug>: SMServer_app: Could
not load custom css file                              
Sep  1 20:15:27 Justins-iPhone SMServer(com.ianwelker.smserver.debugging)[32743] <Debug>: SMServer_app: Could
not load custom css file                              
Sep  1 20:15:29 Justins-iPhone SMServer(com.ianwelker.smserver.debugging)[32743] <Debug>: SMServer_app: Loading server at port 8741                                 
Sep  1 20:15:29 Justins-iPhone SMServer[32743] <Notice>: SMServer_app: Entered obj-c func, launching MobileSMS                                                      
Sep  1 20:15:29 Justins-iPhone SMServer(com.ianwelker.smserver.debugging)[32743] <Debug>: SMServer_app: launched MobileSMS                                          
Sep  1 20:15:29 Justins-iPhone SpringBoard[31413] <Notice>: LibSMServer_app: called LaunchSMS, NO            
Sep  1 20:15:29 Justins-iPhone SMServer(com.ianwelker.smserver.debugging)[32743] <Debug>: SMServer_app: Got past adding all the handlers.                           
Sep  1 20:15:29 Justins-iPhone SMServer(com.ianwelker.smserver.debugging)[32743] <Debug>: SMServer_app: Started websocket successfully.                             
Sep  1 20:15:29 Justins-iPhone SMServer(com.ianwelker.smserver.debugging)[32743] <Debug>: SMServer_app: Successfully started server and launched MobileSMS          
                                                       Ok i got the log.

**Comment by iandwelker** [comment]
Is that everything that showed? It appears to be missing a significant amount; did you happen to respring or lose wifi connection (or something similar) while grabbing the log? Also, did you let it run until you tried to send a text?

**Comment by justin0386** [comment]
![IMG_3426](https://user-images.githubusercontent.com/29316353/92063263-c8d4ea80-ed68-11ea-9c42-5bd79bfdd6d2.PNG)
Thats everything that it showed and yes I ran it all the way through until it crashed

**Comment by iandwelker** [comment]
I think I've found the issue with this and fixed it. It should be working fine by the next update.

**Comment by justin0386** [comment]
Sounds good. I'll let you know if it fixes the issue when you push out the next update.

**Comment by iandwelker** [comment]
I just pushed out the update; it should fix this. When it becomes available, try it out and let me know how it works for you.

**Comment by gnawh** [comment]
now it crashes when i hit start lol
sorry but procuring logs takes a bit too much effort atm

**Comment by justin0386** [comment]
Crashing for me as well. I'll check and see if I still get the same log I was getting though.

**Comment by justin0386** [comment]
Yes I am also still getting the exact same log that I been getting as well.

**Comment by iandwelker** [comment]
@justin0386 Could you try ssh'ing into your device and getting the log that way? I suspect that getting logs via another app on the phone may not show all of them. 
Also, does disabling the `Mark conversations as read when viewed on web interface` option in settings change anything for you?

**Comment by ayserjamshidi** [comment]
On the latest SMServer (0.38) and libsmserver (0.3.2-1+debug) it crashes upon pressing start with the default settings.  This is the logs:
`Sep  6 22:05:05 Aysers-iPhone SMServer(com.ianwelker.smserver.debugging)[3207] <Debug>: SMServer_app: Could not load custom css file
Sep  6 22:05:19 Aysers-iPhone Io[3207] <Notice>: SMServer_app: Entered obj-c func, launching MobileSMS
Sep  6 22:05:19 Aysers-iPhone Io[3207] <Notice>: *** Terminating app due to uncaught exception 'MRYIPCException', reason: 'callExternalMethod:withArguments:completion: - Failed to lookup service port: Unknown service name'`

Line 1 was on starting the app, 2 and 3 are when I press start.

**Comment by iandwelker** [comment]
@ayserjamshidi  And, just to clarify, you've tried the basic things like an ldrestart and reinstalling?

**Comment by ayserjamshidi** [comment]
> @ayserjamshidi And, just to clarify, you've tried the basic things like an `ldrestart` and reinstalling?

Very much so.  I've done excess restarts/ldrestart after uninstalling and then again after reinstalling.

**Comment by iandwelker** [comment]
I realize I may have accidentally build the latest libsmserver without support for A12+ devices; sorry about that. I just updated libsmserver on twickd with support; once it becomes available, try it out and let me know if it fixes the issue.

**Comment by ayserjamshidi** [comment]
That did fix it, good stuff!

**Comment by gnawh** [comment]
unfortunately, crashes for me upon viewing a thread. 
i tried to run your command, but the command oslog is not found.

**Comment by ayserjamshidi** [comment]
> unfortunately, crashes for me upon viewing a thread.
> i tried to run your command, but the command oslog is not found.

You have to get OSLog from Cydia.  Try disabling read receipts, that used to make SMServer crash.

**Comment by gnawh** [comment]
![image](https://user-images.githubusercontent.com/26584539/92566088-8dd32b00-f230-11ea-9b64-b34ccb5dee38.png)

**Comment by gnawh** [comment]
![image](https://user-images.githubusercontent.com/26584539/92566124-99265680-f230-11ea-852f-9f2731750740.png)

**Comment by gnawh** [comment]
read receipts did not make a difference. log above is when I opened a thread to a crash.

**Comment by gnawh** [comment]
downgrading to mryipc 1.0, i can view threads. then i get the old issue of messages **not** **actually being sent**.

**Comment by iandwelker** [comment]
Yes, using the latest version of libsmserver with mryipc 1.0 can cause `MobileSMS.app` to crash, which makes it impossible to send messages. After quite a bit more of testing, I have ran into your issue a few times (and a few others have mentioned the same issue), but it's always at random times and I still have yet to determine what's causing it. Have you yet tried things like disabling all other tweaks to see if one of them could be interfering?

**Comment by gnawh** [comment]
christ my bad. i had choicy whitelist tweaks on mobilesms.app and i never whitelisted libsmserver... sheesh.
i should've done the disable all tweaks thing first. my bad.

thanks for your help! working well now.

**Comment by iandwelker** [comment]
Ah, well I'm glad to hear that it was an easy fix in the end :) Feel free to reopen this issue if things stop working again.
