### ISSUE TITLE
Issues when thread is open in web interface

### ISSUE THREAD

**Issue by londondev77** [iandwelker/smserver#37]
I have a couple of issues when a thread remains open in the web interface:

1. It is automatically marking the thread as read, even if the browser is minimised or I'm on a different tab. This means I'm not getting alerts on my other devices. WhatsApp will only mark things as read when the tab is active. Would it be possible to implement the same?

2. The thread is often not updating as new messages in the thread come in. So I have switch to another thread and back for the new messages to show up.

- iPad 2017
- unc0ver
- iOS 13,5
- Installed through Cydia
- SMServer 0.4.2 and libsmserver 0.3.5

**Comment by iandwelker** [comment]
1. Yes, I can do that; It shouldn't be too hard to implement.

2. This will be significantly harder to diagnose. It would really help if you could enable debug on the app, then watch the browser console as you're having a conversation. It should print something like `parsing message ...` whenever you receive a new text. There's a possibility that the web interface is receiving a notification that you got a new text, but just running into an error when it tries to retrieve it or print it, so watching the browser console will help to narrow down where the error is.
After you watch the browser console, let me know if it does print the `parsing message ...` message when you receive a new text that doesn't show up, and also if it displays any errors as you're watching it.

**Comment by londondev77** [comment]
Here's a console log of messages.  I left this on for a while so apologies if there's a lot of extraneous info.  I tried to capture a more focussed set but for some reason, the console won't update properly now.
https://pastebin.com/Zx5XNqUM

Let me know if this isn't useful and I'll try again.

**Comment by iandwelker** [comment]
No, this is good. It looks like a few errors were thrown which could be causing the new chats to not appear. I don't have much time today but I'll try to check it out and get those issues fixed tomorrow.

**Comment by iandwelker** [comment]
Alright, it was actually quite simple. on line 286 of `chats.html`, it should read `content.appendChild(from);` instead of `doc.appendChild(from);`, which it reads now. I fixed it, so this issue should be gone in the next version. If you don't want to wait though, you can easily open the file `/Applications/SMServer.app/html/chats.html`, find line 286, and change it as described in this message.

**Comment by londondev77** [comment]
Hmmm, it doesn't seem to be working even after restarting server. My PC's ethernet connection is acting weird though so maybe that has something to do with it. Can you keep this ticket open until you've released the fix in the next version?

**Comment by iandwelker** [comment]
Yeah, I can leave this open. I'll update it once I release the next version.

**Comment by londondev77** [comment]
Looks like it's working properly now - thanks for fixing. Would be good to get the first suggestion implemented if it's not too difficult.

**Comment by iandwelker** [comment]
Yup, I actually just got it working, so it'll be included in the next update.

**Comment by iandwelker** [comment]
Version 0.4.3 is now out; it should fix both of these previous issues. Let me know if it doesn't.

**Comment by londondev77** [comment]
Sorry, I entered this bug on the wrong issue thread so I will delete it from there and reposting here.

This has happened a few times so it's not a one-off.  Interestingly, it seems like it's getting mixed up as another thread has a second entry in the message list on the left and this duplicate containst the text from the original thread. Hope that makes some sense!

Here is an image of the web interface:
![193719621-ab32be00-fb7b-11ea-87ef-37fb119a9843](https://user-images.githubusercontent.com/1478538/93879413-91a48a00-fcd3-11ea-886c-53bf96789e19.png)

And then from iMessage:
![293719646-df0de380-fb7b-11ea-9381-1cd0ceeb4045](https://user-images.githubusercontent.com/1478538/93879424-96693e00-fcd3-11ea-977a-ca0a7be723bc.jpg)

Note that on the web, one message is repeated twice instead of showing my reply.

Here's a snippet from the console log:
https://pastebin.com/44VfEQTu

**Comment by iandwelker** [comment]
Have you noticed this happening regularly or does it seem to have been a one-time issue? I've been looking through your log and my code and I can't easily see exactly where the error occurred.

**Comment by londondev77** [comment]
Yes, this has happened a number of times.  It was today that I realised that there was a second entry for the same thread in the list on the left-hand side but it contained text from a different thread.

**Comment by iandwelker** [comment]
Yeah, that happens to me sometimes as well. I suspect these are just race conditions, and that's why they only sometimes happen (e.g. The web interface gets notified that you received a new text before the phone has finished processing the text and entering it into the database, so it doesn't actually grab the most recent text). However, I recently updated to iOS 14 (in which libmryipc, a dependency of this app, is broken), so I may have to halt development on this project for a bit until libmryipc has been fixed. I hope the above issue isn't too much of an inconvenience, since I may not be able to fix it for some time.

**Comment by londondev77** [comment]
👍

**Comment by iandwelker** [comment]
Could you try out version 0.5.0 (just released) and let me know if this issue appears to be fixed?

**Comment by londondev77** [comment]
I'm still seeing the double message I'm afraid. From what I can see, it's when two messages are sent but only one of them is shown twice.  Clicking away and back into the thread then fixes it.

**Comment by iandwelker** [comment]
Could you update to the latest version (0.5.2), turn on debug, and get me a snippet of the browser console log that appears when you run into this issue? I redid the way new texts appear in version 0.5.0, so unfortunately the past snippet you posted doesn't help much.
Also, I'd just like to clarify exactly what's causing this: it sounds like this issue only appears when you send two texts (without attachments or camera roll images) in quick succession, and one of them is duplicated and the other is not shown at all. Is that the case?

**Comment by iandwelker** [comment]
Update: I've actually run into this issue myself now and I'm fairly certain I know what's causing it (just a race condition that occurs when you receive a text right before sending one); I'm rewriting the way that the web interface is notified of new texts to prevent this problem.

**Comment by iandwelker** [comment]
Alright, I've fixed it (actually this time) and will include the fix in the next version. I'll close this issue then, if nobody is still running into duplicating texts.

**Comment by iandwelker** [comment]
Version 0.6.0 of SMServer has not been submitted to Twickd (and is out on this repo), and I am very confident that it fixes this issue. Try it out and let me know if you're still running into this.

**Comment by londondev77** [comment]
I'm really sorry but I'm still having the same issues.  Screenshots below:

When I sent a message, my previous one was shown a second time:
![image](https://user-images.githubusercontent.com/1478538/100591569-de1ccf00-32ed-11eb-97eb-75e1a60d7f44.png)

I then sent a further message and the previous one was displayed:
![image](https://user-images.githubusercontent.com/1478538/100591677-fdb3f780-32ed-11eb-8314-429308353448.png)

When I refreshed, the correct messages were shown:
![image](https://user-images.githubusercontent.com/1478538/100591699-073d5f80-32ee-11eb-9eec-06f2fd1914cc.png)

Let me know if there's anything I can do to help debug. 

As a reminder, I'm on iOS 13.5 running unc0ver 5.3.1

**Comment by iandwelker** [comment]
Could you open the file at `/Applications/SMServer.app/html/chats.html` on your phone and, on line 742, change `var sleep_time = 250` to `var sleep_time = 800`. This will make texts appear to take longer to send, but it may solve this issue (as a temporary fix). If that does it, there are more significant changes I'll have to make to fix this permanently and I'll keep this issue open as I do that.

**Comment by londondev77** [comment]
Done a quick test and definitely seems to be working better however I still got a repeated message at one point.

Also, not sure if this should be raised on a separate ticket but the date/time display for messages seems to go a bit mad and is then resolved when reloading the thread. Similarly, message read indications (to show when the other person has read one of my messages) only seem to update properly when I reload a thread.

Before thread reload:
![image](https://user-images.githubusercontent.com/1478538/100733722-843c0800-33c6-11eb-9c9c-03b1cec9cf99.png)

After thread reload:
![image](https://user-images.githubusercontent.com/1478538/100733734-8aca7f80-33c6-11eb-9cf7-7f501d7d12cb.png)

**Comment by iandwelker** [comment]
Yes, I think I'd prefer we move new problems to a different issue, since this one's gotten somewhat crowded. Feel free to add the information that you just posted here to that new issue, as well.

**Comment by londondev77** [comment]
This appears to be working ok now. I'm facing a number of other bugs and will try to raise some issues if I get the chance.

**Comment by iandwelker** [comment]
I'll close this issue, then.
