### ISSUE TITLE
Website auto update stop working after the device goes in standby

### ISSUE THREAD

**Issue by Andi-bz** [iandwelker/smserver#73]
No new messages after the device goes in standby. If I stay connected thought ssh the service remains active.

**Comment by iandwelker** [comment]
I've noticed this as well on my device -- even when my device's screen is on, the websocket connection seems to die after a minute or so. This is a massive problem, so I'll make sure I get it fixed by the next update.

**Comment by iandwelker** [comment]
@Andi-bz could you disable the "Restart server on network change" option in settings and see if that fixes the issue for you? It seems to fix it for me, though I'm not quite sure why.

**Comment by Andi-bz** [comment]
Seems to disable this setting resolves the problem.

**Comment by sunnydummy** [comment]
Hello, I am from reddit yesterday. It worked last night and then it stopped working this morning. I have changed nothing since then so it just suddenly stopped working. As soon as the screen turns off, it stops working. When i turn the screen back on even without unlocking the phone, it works perfectly fine. I disabled the setting but the problem still consists. I am on 13.5 uncover jailbreak and was wondering if you had any other suggestions?

**Comment by algers** [comment]
> 
> 
> I've noticed this as well on my device -- even when my device's screen is on, the websocket connection seems to die after a minute or so. This is a massive problem, so I'll make sure I get it fixed by the next update.

Try adding the `proxy_read_timeout` directive in the nginx server block. This will override the default setting of 60 seconds to the time specified. I set mine to 7 days and appears to have fixed the issue. 

My full config using a letsencrypt certificate:

```
server {
        listen 80 default_server;

        listen 443 ssl;

        server_name _;
        proxy_ssl_verify off;
        ssl_certificate /config/keys/cert.crt;
        ssl_certificate_key /config/keys/cert.key;

        location / {
                proxy_pass http://10.172.192.10:8741/;
        }

        location /smserver_websocket/ {
            proxy_pass http://10.172.192.10:8740/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_read_timeout 7d;
        }
}
```

**Comment by iandwelker** [comment]
@algers I appreciate the contribution, however I wasn't running SMServer behind a proxy at the time, and I also determined the issue to be caused by the websocket in the web interface not attempting to reconnect after the server restarted due to network change. This issue should be fixed in the next version.

**Comment by iandwelker** [comment]
Version 0.7.1 is out now. It includes fixes to re-connect the websocket if the server restarts due to a network change. It should now work just fine regardless of whether or not you have "Restart server on network change" enabled. Closing issue.

**Comment by sunnydummy** [comment]
this issue still persists for me after updating. That means it has to be a settings issue right? any solutions you can give me?

**Comment by iandwelker** [comment]
I've had a few other people report that they're still running into this as well, so I'll reopen. Could you post your current settings configuration (either with a screenshot or just listing what the current value for each option)? Also, just to clarify: can you still load in different conversations when your screen is locked (but just don't see new texts when they arrive)? Or can you not use SMServer at all when the screen is locked?

**Comment by sunnydummy** [comment]
Hello, thanks for taking time to look at this issue for me

Everything is on default settings. I didn't change any of the numbers. I have the following all enabled: sending typing indicators, automatically mark as seen, require authentication, enable backgrounding, enable SSL, Restart server on network change (disabling this doesnt seem to make a difference).

IPhone SE 2. 13.5 unc0ver jb. 

when the screen is locked, i can click on different conversations but it doesn't open/load. Only the title of the group loads and that is about it. The conversation portion is blank. The smserver only resets when the screen turns on bc of a notification. 5 seconds after you lock the screen smserver will not work on the browser. Basically cannot use smserver at all when the screen is off/locked.

There were however a couple times where it worked flawlessly for a hour but after that it will go back to the same issue. I cannot recall when and at what time it worked. I enabled background refresh on my phone when i usually have it off and that also does not seem to make the

**Comment by iandwelker** [comment]
So although this seems to be the same problem, the root cause of your bug is different from the others who were posting on this issue. Others could load other conversations while the screen was locked, they just couldn't see updates to the battery percentage or updates when new texts came in. However, you can't get anything to load while the screen is locked. 

I personally run into your issue semi-regularly, and the way which your issue is different from others combined with the fact that it randomly fixes itself leads me to believe that it has nothing to do with SMServer. I think what's happening is that your phone is actually temporarily disconnecting from the internet while your screen is off; that's what the issue is for me occasionally. I'd just recommend trying the generic fixes for this; ldrestart, unjailbreak & reboot & rejailbreak, restore rootfs, etc. That's the kinda stuff that normally fixes it for me.

**Comment by sunnydummy** [comment]
Oh it actually works flawless for me now! Thank you so much for taking your time off to work this out for me! All i did was reboot and rejailbreak and it seems to be working for the last 3 hours.

**Comment by iandwelker** [comment]
Glad to hear that! I'll close this issue, then.
